# This is a basic workflow to help you get started with Actions

name: Train and Deploy Model

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  train:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v2
        
    # Connect or Create the Azure Machine Learning Workspace
    - name: Connect/Create Azure Machine Learning Workspace
      id: aml_workspace
      uses: Azure/aml-workspace@v1
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Connect or Create a Compute Target in Azure Machine Learning
    - name: Connect/Create Azure Machine Learning Compute Target
      id: aml_compute_training
      uses: Azure/aml-compute@v1
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

    # Run R script to train model
    - name: Install R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: '3.6.3' # The R version to download (if necessary) and use.

    - name: Check OS version
      run: uname -a

    - name: Install azuremlsdk
      run: |
        options(repos=c("https://packagemanager.rstudio.com/all/__linux__/bionic/latest"))
        install.packages('remotes')
        writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        library(remotes)
        remotes::install_github('https://github.com/Azure/azureml-sdk-for-r')
      shell: Rscript {0}

    - name: Install Azure ML
      run: |
        azuremlsdk::install_azureml()
      shell: Rscript {0}

      ## TODO: Add data to datastore

    - name: Train model
      run: Rscript train-model.R
