# This is a basic workflow to help you get started with Actions

name: Train and Deploy Model

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  train:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v2
        
    # Connect or Create the Azure Machine Learning Workspace
    - name: Connect/Create Azure Machine Learning Workspace
      id: aml_workspace
      uses: Azure/aml-workspace@v1
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Connect or Create a Compute Target in Azure Machine Learning
    - name: Connect/Create Azure Machine Learning Compute Target
      id: aml_compute_training
      uses: Azure/aml-compute@v1
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

    # SSH Connect test
    - name: Connection test
      uses: JimCronqvist/action-ssh@master
      with:
        hosts: ${{ secrets.SHINYUSERNAME }}@${{ secrets.SHINYHOST }}
        privateKey: ${{ secrets.SHINYKEY }}
        command: |
          cd mlops-r-gha
          Rscript test-script.R

    # Connect to the Shiny VM to train the model
    - name: Train model
      uses: JimCronqvist/action-ssh@master
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS}}
      with:
        hosts: ${{ secrets.SHINYUSERNAME }}@${{ secrets.SHINYHOST }}
        privateKey: ${{ secrets.SHINYKEY }}
        command: |
          cd mlops-r-gha
          Rscript train-model.R

    ## TODO: Add data to datastore

    # Connect to the Shiny VM to train the model
    - name: Deploy model
      uses: JimCronqvist/action-ssh@master
      with:
        hosts: ${{ secrets.SHINYUSERNAME }}@${{ secrets.SHINYHOST }}
        privateKey: ${{ secrets.SHINYKEY }}
        command: |
          cd mlops-r-gha
          Rscript deploy-model.R
